### ISSUE TITLE
A question for code of paper "An efficient numerical method for the Generalized Kolmogorov Equation"

### ISSUE THREAD

**Issue by Allenlllee** [davecats/gke#1]
Dear Prof. Gatti,
Can you briefly tell me how to run .cpl written in CPL language?

**Comment by davecats** [comment]
@Allen-magz Dear Allen-magz, the CPL compiler and manual can be found here: https://cplcode.net/

**Comment by Allenlllee** [comment]
okay! Thank you for your kind reply! I will try.

**Comment by Allenlllee** [comment]
One more question, could you kindly provide an input file of database (obtained by DNS code)? I want to see the specific input file format, such as velocity field UVW and pressure field P, or other, etc., Thank you again for everything you did!
You can send me, my email (mgz17@mails.tsinghua.edu.cn), if possible, only one snapshot is ok.

**Comment by davecats** [comment]
@Allen-magz I'll try to upload a Minimal Flow Unit velocity field on GitHub, this may be useful to everyone intereted in the code. I#ll write you when I am done with that.

**Comment by Allenlllee** [comment]
@davecats If so, that would be very nice. Thank you very much! In addition, the program does not seem to have a dedicated output VTK code section?

**Comment by Allen-magz** [comment]
@davecats I'm sorry to bother you again, I have been trying to use this program but failed, I don't know what the problem is, so could you provide a simple running script or instructions, as well as all the necessary files mentioned above to run this program. 
After running the script,  users can obtain some results of **database** folder. Then this will be very helpful for users to get familiar with the program more quickly, modify the program based on your work (following GPL) , and save a lot of time. Of course, this is only my suggestion.
![Uploading 捕获.PNG…]()

**Comment by Allenlllee** [comment]
@davecats I'm sorry to bother you again, I have been trying to use this program but failed, I don't know what the problem is, so could you provide a simple running script or instructions, as well as all the necessary files mentioned above to run this program. 
After running the script,  users can obtain some results of **database** folder. Then this will be very helpful for users to get familiar with the program more quickly, modify the program based on your work (following GPL) , and save a lot of time. Of course, this is only my suggestion.
![problem](https://user-images.githubusercontent.com/82256512/114408356-e8c06c80-9bdb-11eb-822d-e445384f9ed8.PNG)

**Comment by Allenlllee** [comment]
Thank you very much for your kind consideration and I am looking forward to your early reply!

**Comment by davecats** [comment]
@Allen-magz Thank you for your message. Sure, this was a long-due to-do. I'll try to do this asap. I think I'll come to it within one/two weeks. I hope you can understand.

**Comment by Allenlllee** [comment]
@davecats Thank you for your kind support！I fully understand. And I will take good use of the materials. Best wishes!

**Comment by Allen-magz** [comment]
@davecats Sorry to bother you. I think the data file only needs a velocity field at Retau 200, the  mesh is much smaller.

**Comment by Allenlllee** [comment]
Dear Gatti, could the content update be completed by this weekend? Thank you very much.

**Comment by Allenlllee** [comment]
I wonder if author still plans to modify this open-source share files, and when about. if not, i also won't wait and do other things first.

**Comment by davecats** [comment]
Hi @Allen-magz , as you can see I added a directory "./tutoral/". There you find the bash script "run_tutorial.bash", which compiles the code, runs it and then visualises the result. It will run the code on just two fields of a minimal flow unit of a channel flow at Retau=200. The script assumes that you have got a working CPL installation and MATLAB installed on your system. 

This is more or less all I can do. All the rest you can undertand by reading our papers and looking at the code by yourself, with the CPL manual on your desk.
